### ISSUE TITLE
25 Feb 2020 - Team 100 - The Aries - Peer to Peer Review

### ISSUE THREAD

**Issue by kubilaycaglayan** [fdfragoso/Mint-Intuit-Form#1]
1. Input labels will get id's.
2. Form-bottom division should be edited.
3. Screenshot is not working on README.
4. Input number of telephone line should be "tel".
5. Email type should be email.
6. Linters and sticklers should be set.

**Comment by fdfragoso** [comment]
All the listed issues were fixed on the pull request "Stickler CL Install #2".
